# Generated by Django 4.2.5 on 2023-09-27 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machine', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='standard',
            old_name='value_y_max',
            new_name='value_alarm_max',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='value_y_min',
            new_name='value_alarm_min',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='value_z_max',
            new_name='value_danger_max',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='value_z_min',
            new_name='value_danger_min',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='value_x_max',
            new_name='value_safe_max',
        ),
        migrations.RenameField(
            model_name='standard',
            old_name='value_x_min',
            new_name='value_safe_min',
        ),
    ]
